---
title: "**About Me**" 
output:
  html_document: 
    number_sections: false
    toc: true
    toc_depht: 3
    toc_float: true
output_dir: "."
---

<style>
body {
text-align: justify}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color: #990000;
    border-color: transparent;
}


#TOC {
  color: #990000;
  background-color: #990000;
}

</style>


### *Introduction*

As a boundary spanner who thrives on connecting people, I have come to know music as my most important tool for building connections. Allow me to elaborate on how I intend to combine my skillset in communication, data analytics and coordination with my passion for music to the benefit of Sony Music. 


From an early age I was introduced to various musical instruments, but developed a fondness for the piano over time. I currently enjoy playing jazz on the piano and accompanying several talented ( some upcoming) musicians in Berlin on various projects. Some of which you will also find linked on this website.

During my engineering study at the HTW in Berlin, I developed an interest for data science. 

I am also highly enthusiastic about data analytics, using programming tools such as R. 

economics and sociology

musik

modelling self sustaining financing my studies

new beings: interested in change and creating new things


interest about data analytics



As I was building up a strong interest in mathematics and statistics at the same time, I found the combination of economics and sociology the perfect fit, in order to deepen my knowledge about human behavior and statistics.
 

 Through my supplementary subject and focus on organizational sociology, I am particularly aware of the importance of proficient analysis of all dependencies for rational decision-making. 
 
 Therefore I can provide 
Furthermore, my work at New Beings has taught me how important it is to question the status quo, establish structures, and continuously re-evaluate them to effectively bring about change that creates added value for all parties involved. In doing so, I became aware of basic behaviors, such as habit and ignorance, as obstacles to a change process, which made me realize the importance of teamwork and a change of perspective.


### *My passion for Data*
In my ongoing studies I had the chance to gain a large skill set in a variety of topics regarding statistics and data analysis. Throughout courses in R and STATA I became familiar with the modern tools of data analysis and the endless possibilities in edit, analyse and visualize data. Since then I'm familiar with the process of data wrangling, cleaning and I have a deep understanding of descriptive and inferential statistics. In decision solid foundation of well analysed data always needs to be at hand, but not only the data needs to be analyse it as well needs to be visualized and communicated adequately to those who take a decision. I have a knowledge of data visualisation and data collection through methods such as web-scraping. Therefore I see myself trained enough to provide sufficient information for rational decision making.


