---
title: "**My Web-CV**" 
output:
  html_document:
    theme: cosmo
output_dir: "."
---


<style>
body {
text-align: justify}

.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px;
    color: #990000;
}
.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
    color: #ffffff;
    background-color: #990000;
}

a:link {
  color: #990000;
  background-color: transparent;
  text-decoration: none;
}

a:visited {
  color: pink;
  background-color: transparent;
  text-decoration: none;
}

a:hover {
  color: darkblue;
  background-color: transparent;
  text-decoration: underline;
}

a:active {
  color: yellow;
  background-color: transparent;
  text-decoration: underline;
}

</style>

### *Welcome to my online application* {.tabset .tabset-fade .tabset-pills}


#### What this webpage is about {.tabset}
* With this webpage I would like to express my sincere interest in the position as a <a href="https://www.sonymusic.de/job/werkstudentin-m-w-d-market-analytics/" rel="noopener noreferrer" target="_parent">working student in market analytics</a> at Sony Music. I'd like to showcase my combined skill set in communication, data analytics, coordination, and passion for music and proof how they can be beneficial to Sony Music. You will find all necessary information here to get to know me a little better and get an idea what my motivation is. If you would like to jump directly to a quick overview, please click <a href="https://fabio-auerswald.github.io/Resume.html "rel="noopener noreferrer" target="_parent">here</a>.


#### What can be found on this webpage {.tabset}
* A Resume, with detailed information about my education, work experience and further skills
* An introduction section
* References to my musical activities and examples of my coding
* Contact info


#### How this webpage was created {.tabset}
* This webpage was built with RStudio using the documentation tool RMarkdown including html, CSS and Github      Pages for publishing it on the internet.





